export const CREATE_PLAYERS = 'CREATE_PLAYERS';
export const CREATE_PLAYERS_SUCCESS = 'CREATE_PLAYERS_SUCCESS';
export const ROLL_THE_DICE = 'ROLL_THE_DICE';
export const ROLL_THE_DICE_SUCCESS = 'ROLL_THE_DICE_SUCCESS';
