export const CREATE_PLAYERS = 'CREATE_PLAYERS';
export const CLEAR_GAME = 'CLEAR_GAME';
export const CREATE_PLAYERS_SUCCESS = 'CREATE_PLAYERS_SUCCESS';
export const ROLL_THE_DICE = 'ROLL_THE_DICE';
export const ROLL_THE_DICE_SUCCESS = 'ROLL_THE_DICE_SUCCESS';
export const PLAYER_SCORED_6 = 'PLAYER_SCORED_6';
export const CLEAR_PLAYER_SCORED_6 = 'CLEAR_PLAYER_SCORED_6';
export const CLEAR_TWICE_ONE = 'CLEAR_TWICE_ONE';
